[features]
seeds = false
skip-lint = false
[programs.localnet]
tic_tac_toe = "6kTBYbV3itwchJZmT5wzPoWHiwzFwB5zCoHJmuYdYcVX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/shubh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
